### ISSUE TITLE
subject.pdf's link does not exit

### ISSUE THREAD

**Issue by Valerianofilipec** [rphlr/42-Evals#13]
**Describe the bug**
The link to open the evaluation sheet's subject.pdf doesn't work, since the API's response never returns a cdn link to reach the subject. 

**To Reproduce**
 - open any evaluation sheet, and see that the link to the subject doesn't work.

**Expected behavior**
A link to the subject (from the 42's CDN or the database, i.e. https://cdn.intra.42.fr/pdf/pdf/138347/en.subject.pdf ) is expected in sheetData.attachments

**Screenshots**
![Screenshot 2024-08-29 at 6 14 42 PM](https://github.com/user-attachments/assets/c4e46d3e-2ece-4e20-ba26-050121b931e8)
![Screenshot 2024-08-29 at 6 15 47 PM](https://github.com/user-attachments/assets/8e11efb0-d325-4db4-8595-6e92a0ccab86)
![Screenshot 2024-08-29 at 6 18 26 PM](https://github.com/user-attachments/assets/b1b991ec-57e4-4d10-93b1-5f95891fa690)
![Screenshot 2024-08-29 at 6 19 45 PM](https://github.com/user-attachments/assets/79287413-5fc4-4360-a220-d0841aa928be)

**Comment by rphlr** [comment]
Hi @Valerianofilipec alerianofilipec,

Thanks for bringing this to my attention. Currently, the PDF attachments for the evaluation sheets are not available. This is due to image rights and usage policies imposed by the Network and it’s uncertain if these PDFs will be made available in the future.

I’m working on a solution and will keep you updated on any progress. For now, the PDF links are not included, but I appreciate your understanding on this matter.

If you have any other questions or issues, please let me know.

Best regards,
Raphael
