### ISSUE TITLE
so_long bonus

### ISSUE THREAD

**Issue by veliga-syutkin** [rphlr/42-Evals#6]
In the so_long subject, one of bonuses is: 
`Display the movement count directly on screen instead of writing it in the shell.`

But in the present evaluation sheet, there isn't any mention of it. Is it same in official evaluation sheet?

**Comment by rphlr** [comment]
> In the so_long subject, one of bonuses is: 
> `Display the movement count directly on screen instead of writing it in the shell.`
> 
> But in the present evaluation sheet, there isn't any mention of it. Is it same in official evaluation sheet? 

Hello! Are you sure? I recall having it when I did the project a year ago! However, things might have changed since then. Thank you for your report, I'll verify this. All the evaluation sheets were downloaded from the official website, so there may have been changes since then. If you've downloaded the HTML correction from the website or have done a screenshot of it, I can update the information. :)

**Comment by veliga-syutkin** [comment]
Hi, to be honest, I just started the project and on top of that, I've never got to correct this one... As soon I get more info, I'll share it asap!

**Comment by veliga-syutkin** [comment]
Hi, 
I validated so_long without bonuses. 
Your sheet is good, sorry for inconvenience. 
Looks like I've overseen when first time looking the counter where it tells there should be a counter, and it can be displayed in the terminal and/or the game itself. 
Best regards,

**Comment by rphlr** [comment]
Congrats then 😄 🎉
